### PR TITLE
New helper method added to fetch model fields and respective contents

### PR DESCRIPTION
**Pull request by adam-murray**
This helper method is useful when adding new versioned models.

### CODE REVIEW

**Comment by jonathan-s** [comment]
@adam-murray Is this used anywhere, or are there plans for this to be used?

**Comment by adam-murray** [comment]
@jonathan-s sorry didn't see your message! Every versioned model content requires a variation of this method. It will be useful for the cms4 eco-system in general although there are no specific uses for it within versioning itself at this time.

**Comment by jonathan-s** [comment]
@adam-murray Once there is a repo which would like to use this method, you can link it to this PR and say that it depends on this PR. I'd say that only then is it justified to merge this in.

**Comment by Aiky30** [comment]
Closing as dated and conflicting.

**Pull request closed without merging**
